version: "3"

services:
  mariadb-server:
    image: mariadb
    container_name: mariadb-server
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=devpassword
    ports:
      - 3306:3306  # for interop with locahost

  postgres-server:
    image: postgres
    container_name: postgres-server
    restart: always
    volumes:
      - "/tmp/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=devpassword
    ports:
      - 5432:5432  # for interop with locahost

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mariadb-proxy:
    image: rust
    container_name: mariadb-proxy
    command: /bin/bash -c "while true; do sleep 200; echo 'TERMINAL is up'; done"
    volumes:
      - "./:/code"
    working_dir: /code
    ports:
      - "26658:26658"
    links:
      - mariadb-server
      - postgres-server

  tendermint:
    image: tendermint/tendermint:v0.32.8
    container_name: tendermint-node
    entrypoint: /bin/sh -c "tendermint init && tendermint unsafe_reset_all && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://mariadb-proxy:26658 --rpc.laddr=tcp://0.0.0.0:26657"
    volumes:
      - "/tmp/tendermint:/tendermint"
    links:
      - mariadb-server
      - postgres-server
      - mariadb-proxy
